### ISSUE TITLE
can't find the element if page loaded hashtag site

### ISSUE THREAD

**Issue by d4op** [anniedotexe/Instagram-Like-Comment-Bot#5]
can't find the element if page loaded hashtag site.
login working.
opening hashtag site working.
failed finding posts 

selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='react-root']/div/div/section/main/article/div[1]/div/div/div[1]/div[1]/a/div/div[2]"}
  (Session info: chrome=94.0.4606.71)

**Comment by anniedotexe** [comment]
This is probably the same as the other opened issue - I just haven't had the time to update the X-paths. Will fix it soon.
