### ISSUE TITLE
Logs in and goes to hashtag, then it throws an error

### ISSUE THREAD

**Issue by Ampdale** [anniedotexe/Instagram-Like-Comment-Bot#6]
C:\Users\user\Desktop\Instagram-Like-Comment-Bot-master\insta-bot.py:92: DeprecationWarning: find_element_by_* commands are deprecated. Please use find_element() instead
  first_thumbnail = browser.find_element_by_xpath(
Traceback (most recent call last):
  File "C:\Users\user\Desktop\Instagram-Like-Comment-Bot-master\insta-bot.py", line 92, in <module>
    first_thumbnail = browser.find_element_by_xpath(
  File "F:\Python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 514, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "F:\Python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1238, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "F:\Python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 418, in execute
    self.error_handler.check_response(response)
  File "F:\Python\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='react-root']/div/div/section/main/article/div[1]/div/div/div[1]/div[1]/a/div/div[2]"}
  (Session info: chrome=95.0.4638.69)
Stacktrace:
Backtrace:
        Ordinal0 [0x009F0C43+2493507]
        Ordinal0 [0x0098A4B1+2073777]
        Ordinal0 [0x00892608+1058312]
        Ordinal0 [0x008BCAA4+1231524]
        Ordinal0 [0x008E6C62+1404002]
        Ordinal0 [0x008D597A+1333626]
        Ordinal0 [0x008E5038+1396792]
        Ordinal0 [0x008D580B+1333259]
        Ordinal0 [0x008B2314+1188628]
        Ordinal0 [0x008B316F+1192303]
        GetHandleVerifier [0x00B77BF6+1548950]
        GetHandleVerifier [0x00C2461C+2256060]
        GetHandleVerifier [0x00A7C13B+518107]
        GetHandleVerifier [0x00A7B1E0+514176]
        Ordinal0 [0x0098F53D+2094397]
        Ordinal0 [0x00993418+2110488]
        Ordinal0 [0x00993552+2110802]
        Ordinal0 [0x0099CE81+2150017]
        BaseThreadInitThunk [0x75DEFA29+25]
        RtlGetAppContainerNamedObjectPath [0x76F97A9E+286]
        RtlGetAppContainerNamedObjectPath [0x76F97A6E+238]

**Comment by anniedotexe** [comment]
This is probably the same as the other opened issue - I just haven't had the time to update the X-paths. Will fix it soon.
