### ISSUE TITLE
I can't press the login button.

### ISSUE THREAD

**Issue by sho-wn** [anniedotexe/Instagram-Like-Comment-Bot#8]
Hi, thank you for sharing the great code.
I tried to run insta-bot.py on VSCode but not running.

I was able to enter my username and password automatically, but before I could press the login button, I was redirected to the hashtag search screen.

What I did was to create a credentials.py file and write the username and password.
I also wrote the path to ChromeDriver in config.py.

Thank you.

**Comment by anniedotexe** [comment]
Hello,

Thanks for letting me know about this.
I run my tests on a separate folder and then copy and paste whatever
updated code into the folder that is synced with the GitHub repo. I may
have missed a line. Will get that fixed by the end of today.

Best,
A

**Comment by anniedotexe** [comment]
@sho-wn Hello, this has been fixed.

**Comment by sho-wn** [comment]
@anniedotexe 

Thank You !

I have confirmed that I can log in.
Thank you.

But there is a problem with the next step.

The hashtag is searched, but the process ends without opening the post.
Sorry for all the rudimentary questions.

Best regards.

**Comment by anniedotexe** [comment]
No worries, I was able to run the updated code with no problem. It might be
a newer version of Selenium that you are using, I think I have an older
version from when I first created the bot. Will check on it later.

**Comment by anniedotexe** [comment]
@sho-wn It looks like the selenium version I currently have (that the project works with) is 3.141.0

You can uninstall your current version with `pip uninstall selenium` and then install this version of selenium with `pip install selenium==3.141.0`

Then the code should work.

**Comment by sho-wn** [comment]
Thanks for confirming.

How can I check the version of selenium on VSCODE?
When I search in Finder, I get 3.141 and 4.1.2.
The environment I am using is OS X and VS CODE.

**Comment by anniedotexe** [comment]
I think you can run the 2 pip uninstall/install in the terminal in VSCODE
to change the version of Selenium for just this project.

**Comment by sho-wn** [comment]
I re-installed selenium as you taught me.
I was also able to confirm that my code worked so far.
Thank you.

However, I still can't open the post after the hashtag search.
I will paste my command.
If it doesn't work next time, I'll give up.
I can't be bothered by you any more.

`Traceback (most recent call last):
  File "/Users/mbp/MyFilePath/Instagram-Like-Comment-Bot-master/insta-bot.py", line 74, in <module>
    first_thumbnail = browser.find_element_by_xpath(
  File "/Users/mbp/.pyenv/versions/3.8.9/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/Users/mbp/.pyenv/versions/3.8.9/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/Users/mbp/.pyenv/versions/3.8.9/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/mbp/.pyenv/versions/3.8.9/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div/div/section/main/article/div[1]/div/div/div[1]/div[1]/a/div/div[2]"}
  (Session info: chrome=98.0.4758.109)`

**Comment by anniedotexe** [comment]
The bot works on Windows.

Someone else who uses Mac let me know they had the same problem as you.

If you are using Mac, this article may help -
https://dev.to/kahawaiikailana/running-selenium-on-a-mac-troubleshooting-guide-4fd5

I don't have a Mac device, so can't help you with that anymore. You can
always Google for more articles regarding running Selenium on Mac, but this
is out of my expertise. I do not have time for side projects right now.

Best,
A
