### ISSUE TITLE
idk why 

### ISSUE THREAD

**Issue by chris2kgg** [anniedotexe/Instagram-Like-Comment-Bot#9]
idk why 

Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[1]/div/div/section/main/article/div[1]/div/div/div[1]/div[1]/a/div/div[2]"}

**Comment by 0xr22** [comment]
Same problem here. Seems like the owner of this repo wont fix it. Have you got it fixed by urself?

**Comment by OlinRB** [comment]
Change xpath on thumbnail click to "/html/body/div[1]/div/div[1]/div/div[1]/div/div/div/div[1]/div[1]/section/main/article/div[1]/div/div/div[1]/div[1]/a/div[1]/div[2]"

**Comment by anniedotexe** [comment]
has been updated
